import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from io import BytesIO
# # from user_performance_calc import (
# #     load_data, remove_grand_total_row, filter_columns, clean_numeric_columns, 
# #     split_CreatedBy_column, add_additional_info, split_guest_column, convert_date_format,
# #     columns_to_keep, competition_fixture, total_budget_packages_data,
# #     total_budget_target_data
# )
from tjt_hosp_api import filtered_df_without_seats

def run_app():
    # Your existing User Performance code
    specified_users = ['dcoppin', 'Jedwards', 'jedwards', 'bgardiner', 'BenT', 'jmurphy', 'ayildirim',
                       'MeganS', 'BethNW', 'HayleyA', 'LucyB', 'Conor', 'SavR', 'MillieS']

    arsenal_gold = '#DAA520'

    st.title('👤 AFC Premium Exec Dashboard 👤')

    st.markdown("""
    ### ℹ️ About
    This application provides detailed Exec Sales Metrics ONLY, derived from RTS data. The data is retrieved from TJT's MBM sales API. The app allows you to filter results by date, user, and fixture for tailored insights.
    """)

    loaded_api_df = filtered_df_without_seats

    if loaded_api_df is not None:
        st.sidebar.success("✅ Data retrieved successfully.")
        progress_bar = st.sidebar.progress(0)
        progress_bar.progress(10)
        progress_bar.progress(30)
        progress_bar.progress(50)
        progress_bar.progress(100)

        # Sidebar Features
        date_range = st.sidebar.date_input("📅 Select Date Range", [])
        valid_usernames = [user for user in specified_users if user in pd.unique(loaded_api_df['CreatedBy'])]
        event_names = pd.unique(loaded_api_df['Fixture Name'])
        selected_events = st.sidebar.multiselect("🎫 Select Events", options=event_names, default=event_names)
        selected_users = st.sidebar.multiselect("👤 Select Execs", options=valid_usernames, default=valid_usernames)
        # payment_status_options = pd.unique(loaded_api_df['Payment status'])
        # selected_payment_status = st.sidebar.multiselect("💳 Select Payment Status", options=payment_status_options, default=None)
        paid_options = pd.unique(loaded_api_df['IsPaid'])
        selected_paid = st.sidebar.selectbox("💰 Filter by IsPaid", options=paid_options) 

        # Initialize filtered_data with processed_data to ensure no errors occur if no filters are applied
        filtered_data = loaded_api_df.copy()

        if date_range:
            min_date, max_date = (pd.Timestamp(date_range[0]), pd.Timestamp(date_range[1]) if len(date_range) == 2 else pd.Timestamp(date_range[0]))
            filtered_data = filtered_data[
                (filtered_data['CreatedOn'] >= min_date) &
                (filtered_data['CreatedOn'] <= max_date)
            ]

        if selected_users:
            filtered_data = filtered_data[filtered_data['CreatedBy'].isin(selected_users)]

        if selected_events:
            filtered_data = filtered_data[filtered_data['Fixture Name'].isin(selected_events)]

        # Apply paid status filter
        if selected_paid:
            filtered_data = filtered_data[filtered_data['IsPaid'] == selected_paid]

        # Apply payment status filter
        # if selected_payment_status:
        #     filtered_data = filtered_data[filtered_data['Payment status'].isin(selected_payment_status)]

        # Only proceed if filtered_data is not empty
        if not filtered_data.empty:
            chart_size = (8, 4)
            font_size_title = 14
            font_size_labels = 10

            st.write("### 💼 Total Sales Generated by Exec")
            total_sold = filtered_data['TotalPrice'].sum()
            st.write(f"**Total Accumulated Sales by Premium Exec Team: £{total_sold:,.2f}**")
            
            total_package_sales_by_exec = filtered_data.groupby('CreatedBy')['TotalPrice'].sum().reset_index()
            total_package_sales_by_exec['TotalPrice'] = total_package_sales_by_exec['TotalPrice'].apply(lambda x: f"£{x:,.2f}")
            st.dataframe(total_package_sales_by_exec)
            
            fig, ax = plt.subplots(figsize=chart_size)
            ax.bar(total_package_sales_by_exec['CreatedBy'], filtered_data.groupby('CreatedBy')['TotalPrice'].sum(), color=arsenal_gold)
            ax.set_title('Total Package Sales by Exec', fontsize=font_size_title)
            ax.set_xlabel('Exec', fontsize=font_size_labels)
            ax.set_ylabel('Total Package Sales (£)', fontsize=font_size_labels)
            plt.xticks(rotation=45, ha='right', fontsize=font_size_labels)
            plt.yticks(fontsize=font_size_labels)
            st.pyplot(fig)

            st.write("### 📊 Average Sale Value per Exec")
            avg_sale_value_per_exec = filtered_data.groupby('CreatedBy')['TotalPrice'].mean().reset_index()
            avg_sale_value_per_exec['TotalPrice'] = avg_sale_value_per_exec['TotalPrice'].apply(lambda x: f"£{x:,.2f}")
            st.dataframe(avg_sale_value_per_exec)

            fig, ax = plt.subplots(figsize=chart_size)
            ax.bar(avg_sale_value_per_exec['CreatedBy'], filtered_data.groupby('CreatedBy')['TotalPrice'].mean(), color=arsenal_gold)
            ax.set_title('Average Sale Value per Exec', fontsize=font_size_title)
            ax.set_xlabel('Exec', fontsize=font_size_labels)
            ax.set_ylabel('Average Sale Value (£)', fontsize=font_size_labels)
            plt.xticks(rotation=45, ha='right', fontsize=font_size_labels)
            plt.yticks(fontsize=font_size_labels)
            st.pyplot(fig)

            st.write("### 🧮 Total Count of Sales by Exec")
            total_sales_count_by_exec = filtered_data.groupby('CreatedBy').size().reset_index(name='Total Sales')
            st.dataframe(total_sales_count_by_exec)

            fig, ax = plt.subplots(figsize=chart_size)
            ax.bar(total_sales_count_by_exec['CreatedBy'], total_sales_count_by_exec['Total Sales'], color=arsenal_gold)
            ax.set_title('Total Number of Sales per Exec', fontsize=font_size_title)
            ax.set_xlabel('Exec', fontsize=font_size_labels)
            ax.set_ylabel('Total Sales', fontsize=font_size_labels)
            plt.xticks(rotation=45, ha='right', fontsize=font_size_labels)
            plt.yticks(fontsize=font_size_labels)
            st.pyplot(fig)

            st.write("### 🏷️ Total Discounts Given per Exec")
            total_discounts_given_by_exec = filtered_data.groupby('CreatedBy')['DiscountValue'].sum().reset_index()
            total_discounts_given_by_exec['DiscountValue'] = total_discounts_given_by_exec['DiscountValue'].apply(lambda x: f"£{x:,.2f}")
            st.dataframe(total_discounts_given_by_exec)

            fig, ax = plt.subplots(figsize=chart_size)
            ax.bar(total_discounts_given_by_exec['CreatedBy'], filtered_data.groupby('CreatedBy')['DiscountValue'].sum(), color=arsenal_gold)
            ax.set_title('Total Discounts Given per Exec', fontsize=font_size_title)
            ax.set_xlabel('Exec', fontsize=font_size_labels)
            ax.set_ylabel('Total Discounts (£)', fontsize=font_size_labels)
            plt.xticks(rotation=45, ha='right', fontsize=font_size_labels)
            plt.yticks(fontsize=font_size_labels)
            st.pyplot(fig)

            st.write("### 📈 Revenue Contribution Percentage per Exec")
            total_revenue = filtered_data['TotalPrice'].sum()
            revenue_contribution_percentage = filtered_data.groupby('CreatedBy')['TotalPrice'].sum().reset_index()
            revenue_contribution_percentage['Contribution (%)'] = (revenue_contribution_percentage['TotalPrice'] / total_revenue) * 100
            revenue_contribution_percentage['Contribution (%)'] = revenue_contribution_percentage['Contribution (%)'].apply(lambda x: f"{x:.2f}%")
            st.dataframe(revenue_contribution_percentage[['CreatedBy', 'Contribution (%)']])

            fig, ax = plt.subplots(figsize=chart_size)
            ax.bar(revenue_contribution_percentage['CreatedBy'], filtered_data.groupby('CreatedBy')['TotalPrice'].sum() / total_revenue * 100, color=arsenal_gold)
            ax.set_title('Revenue Contribution Percentage per Exec', fontsize=font_size_title)
            ax.set_xlabel('Exec', fontsize=font_size_labels)
            ax.set_ylabel('Contribution (%)', fontsize=font_size_labels)
            plt.xticks(rotation=45, ha='right', fontsize=font_size_labels)
            plt.yticks(fontsize=font_size_labels)
            st.pyplot(fig)

            output = BytesIO()
            output.write(filtered_data.to_csv(index=False).encode('utf-8'))
            output.seek(0)

            st.download_button(
                label="💾 Download Filtered Data for In-depth Analysis",
                data=output,
                file_name='filtered_sales_data.csv',
                mime='text/csv',
            )
        else:
            st.warning("⚠️ No data available for the selected filters.")
    else:
        st.sidebar.warning("🚨 Please upload a file to proceed.")

if __name__ == "__main__":
    run_app()
